name: Check

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Copy gradle.properties file
      run: cp app/gradle.properties.example app/gradle.properties

    - name: Run the linter and unit tests
      run: ./gradlew check

    - name: Run instrumented UI tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck
